[build]
base = "lina-curation-dashboard"
command = "pnpm run build"
publish = "dist"

# SPA fallback global: qualquer rota deve servir index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
