[build]
base = "lina-curation-dashboard"
command = "pnpm run build"
publish = "dist"

# Só redireciona a rota /feed e suas subrotas para o index.html
[[redirects]]
from = "/feed"
to = "/index.html"
status = 200

[[redirects]]
from = "/feed/*"
to = "/index.html"
status = 200
