[build]
base = "lina-curation-dashboard"
command = "pnpm run build"
publish = "dist"

# SPA fallback: redireciona quaisquer rotas do app para o index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
